CREATE TABLE IF NOT EXISTS plugin_global_settings (
    plugin_name VARCHAR(100) NOT NULL PRIMARY KEY,
    settings_json LONGTEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
