<?php
$formId = 'display';
$title = $display ? __('display.edit_title') : __('display.create_title');
require __DIR__ . '/../layouts/admin_header.php';
?>
<h1><?= e($title) ?></h1>
<?php if ($error): ?><div class="alert error"><?= e($error) ?></div><?php endif; ?>
<div class="display-form-layout">
    <div class="card">
        <form method="post" action="<?= e($display ? url('/admin/displays/' . $display['id'] . '/edit') : url('/admin/displays/create')) ?>" class="form-grid">
            <?= csrf_field() ?>
            <label><?= e(__('common.name')) ?>
                <input type="text" id="display_name" name="name" value="<?= e((string)old('name', $display['name'] ?? '', $formId)) ?>" placeholder="<?= e(__('display.name_placeholder')) ?>" required<?= field_attrs('name', $formId) ?>>
                <?= field_error_html('name', $formId) ?>
            </label>
            <label><?= e(__('display.human_url')) ?>
                <input type="text" id="display_slug" name="slug" value="<?= e((string)old('slug', $display['slug'] ?? '', $formId)) ?>" placeholder="<?= e(__('display.slug_placeholder')) ?>" required<?= field_attrs('slug', $formId) ?>>
                <?= field_error_html('slug', $formId) ?>
                <small class="field-note"><?= e(__('display.slug_autogenerated_hint')) ?></small>
            </label>
            <label><?= e(__('channel.transition_effect')) ?>
                <select name="transition_effect"<?= field_attrs('transition_effect', $formId) ?>>
                    <?php foreach (['fade','slide-left','slide-right','slide-up','slide-down','zoom','flip','blur','none'] as $fx): ?>
                        <option value="<?= e($fx) ?>" <?= old_selected('transition_effect', $fx, $display['transition_effect'] ?? 'fade', $formId) ?>><?= e(enum_label('effects', $fx, $fx)) ?></option>
                    <?php endforeach; ?>
                </select>
                <?= field_error_html('transition_effect', $formId) ?>
            </label>
            <label><?= e(__('common.orientation')) ?>
                <select name="orientation"<?= field_attrs('orientation', $formId) ?>>
                    <option value="landscape" <?= old_selected('orientation', 'landscape', $display['orientation'] ?? 'landscape', $formId) ?>><?= e(enum_label('orientations', 'landscape')) ?></option>
                    <option value="vertical" <?= old_selected('orientation', 'vertical', $display['orientation'] ?? 'landscape', $formId) ?>><?= e(enum_label('orientations', 'vertical')) ?></option>
                </select>
                <?= field_error_html('orientation', $formId) ?>
            </label>
            <label><?= e(__('display.default_slide_duration')) ?>
                <input type="number" min="1" name="slide_duration_seconds" value="<?= e((string)old('slide_duration_seconds', $display['slide_duration_seconds'] ?? 8, $formId)) ?>" placeholder="<?= e(__('display.duration_placeholder')) ?>" required<?= field_attrs('slide_duration_seconds', $formId) ?>>
                <?= field_error_html('slide_duration_seconds', $formId) ?>
            </label>
            <label><?= e(__('common.timezone')) ?>
                <input type="text" name="timezone" value="<?= e((string)old('timezone', $display['timezone'] ?? 'UTC', $formId)) ?>" placeholder="<?= e(__('display.timezone_placeholder')) ?>" required<?= field_attrs('timezone', $formId) ?>>
                <?= field_error_html('timezone', $formId) ?>
            </label>
            <label><?= e(__('common.sort_order')) ?>
                <input type="number" min="0" name="sort_order" value="<?= e((string)old('sort_order', $display['sort_order'] ?? 0, $formId)) ?>" placeholder="<?= e(__('display.sort_order_placeholder')) ?>"<?= field_attrs('sort_order', $formId) ?>>
                <?= field_error_html('sort_order', $formId) ?>
            </label>
            <label class="full-width"><?= e(__('common.description')) ?>
                <textarea name="description" rows="4" placeholder="<?= e(__('display.description_placeholder')) ?>"<?= field_attrs('description', $formId) ?>><?= e((string)old('description', $display['description'] ?? '', $formId)) ?></textarea>
                <?= field_error_html('description', $formId) ?>
            </label>
            <label class="checkbox-row"><input type="checkbox" name="is_active" value="1" <?= old_checked('is_active', $display['is_active'] ?? 1, $formId) ?>> <?= e(__('common.active')) ?></label>
            <div class="form-actions"><button type="submit" class="button button--default"><?= admin_icon('save') ?><span><?= e(__('common.save')) ?></span></button><a class="button button--normal" href="<?= e(url('/admin/displays')) ?>"><?= admin_icon('cancel') ?><span><?= e(__('common.cancel')) ?></span></a></div>
        </form>
    </div>

    <aside class="card heartbeat-sidebar">
        <h2><?= e(__('display.heartbeat_title')) ?></h2>
        <?php if ($display): ?>
            <form method="post" action="<?= e(url('/admin/displays/' . $display['id'] . '/reload')) ?>" class="form-actions">
                <?= csrf_field() ?>
                <input type="hidden" name="return_to" value="<?= e('/admin/displays/' . $display['id'] . '/edit') ?>">
                <button type="submit" class="button button--normal"><?= admin_icon('reload') ?><span><?= e(__('display.reload_slideshow')) ?></span></button>
            </form>
            <p class="muted"><?= e(__('display.reload_hint')) ?></p>
        <?php endif; ?>
        <?php if (!$display): ?>
            <p class="muted"><?= e(__('display.heartbeat_save_first')) ?></p>
        <?php elseif (!$heartbeat): ?>
            <p class="muted"><?= e(__('display.heartbeat_none')) ?></p>
        <?php else: ?>
            <?php $isOnline = ((strtotime((string)$heartbeat['last_seen_at']) ?: 0) >= (time() - 1800)); ?>
            <dl class="meta-list">
                <div><dt><?= e(__('common.status')) ?></dt><dd><span class="status-dot status-<?= e($isOnline ? 'online' : 'offline') ?>"></span> <?= e($isOnline ? __('common.online') : __('common.offline')) ?></dd></div>
                <div><dt><?= e(__('display.current_channel')) ?></dt><dd><?= e($heartbeat['current_channel_name'] ?: __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.last_seen')) ?></dt><dd><?= e($heartbeat['last_seen_at'] ?: __('common.never')) ?></dd></div>
                <div><dt><?= e(__('common.client_ip')) ?></dt><dd><?= e($heartbeat['last_seen_ip'] ?: __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('common.browser')) ?></dt><dd><?= e(trim(($heartbeat['browser_name'] ?: __('common.unknown')) . ' ' . ($heartbeat['browser_version'] ?: ''))) ?></dd></div>
                <div><dt><?= e(__('common.operating_system')) ?></dt><dd><?= e(trim(($heartbeat['os_name'] ?: __('common.unknown')) . ' ' . ($heartbeat['os_version'] ?: ''))) ?></dd></div>
                <div><dt><?= e(__('common.viewport')) ?></dt><dd><?= e(($heartbeat['viewport_width'] ?: '?') . ' × ' . ($heartbeat['viewport_height'] ?: '?')) ?></dd></div>
                <div><dt><?= e(__('common.screen_resolution')) ?></dt><dd><?= e(($heartbeat['screen_width'] ?: '?') . ' × ' . ($heartbeat['screen_height'] ?: '?')) ?></dd></div>
                <div><dt><?= e(__('display.available_screen')) ?></dt><dd><?= e(($heartbeat['avail_screen_width'] ?: '?') . ' × ' . ($heartbeat['avail_screen_height'] ?: '?')) ?></dd></div>
                <div><dt><?= e(__('display.screen_orientation')) ?></dt><dd><?= e($heartbeat['screen_orientation'] ?: __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.pixel_ratio')) ?></dt><dd><?= e($heartbeat['device_pixel_ratio'] !== null ? (string)$heartbeat['device_pixel_ratio'] : __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.color_depth')) ?></dt><dd><?= e($heartbeat['color_depth'] !== null ? (string)$heartbeat['color_depth'] . ' bit' : __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('common.platform')) ?></dt><dd><?= e($heartbeat['platform'] ?: __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('common.language')) ?></dt><dd><?= e($heartbeat['language'] ?: __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.client_timezone')) ?></dt><dd><?= e($heartbeat['client_timezone'] ?: __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.cpu_threads')) ?></dt><dd><?= e($heartbeat['hardware_concurrency'] !== null ? (string)$heartbeat['hardware_concurrency'] : __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.device_memory')) ?></dt><dd><?= e($heartbeat['device_memory_gb'] !== null ? (string)$heartbeat['device_memory_gb'] . ' GB' : __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.touch_points')) ?></dt><dd><?= e($heartbeat['max_touch_points'] !== null ? (string)$heartbeat['max_touch_points'] : __('common.unknown')) ?></dd></div>
                <div><dt><?= e(__('display.navigator_online')) ?></dt><dd><?= e($heartbeat['is_online'] === null ? __('common.unknown') : ($heartbeat['is_online'] ? __('common.yes') : __('common.no'))) ?></dd></div>
                <div><dt><?= e(__('display.cookies_enabled')) ?></dt><dd><?= e($heartbeat['cookies_enabled'] === null ? __('common.unknown') : ($heartbeat['cookies_enabled'] ? __('common.yes') : __('common.no'))) ?></dd></div>
                <div><dt><?= e(__('display.user_agent')) ?></dt><dd class="mono"><?= e($heartbeat['user_agent'] ?: __('common.unknown')) ?></dd></div>
            </dl>
        <?php endif; ?>
    </aside>
</div>

<script>
(() => {
    const nameInput = document.getElementById('display_name');
    const slugInput = document.getElementById('display_slug');
    if (!nameInput || !slugInput) return;

    const initialSlug = slugInput.value.trim();
    let slugTouched = initialSlug !== '';

    const slugify = value => value
        .toLowerCase()
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        || 'display';

    nameInput.addEventListener('input', () => {
        if (slugTouched) return;
        slugInput.value = slugify(nameInput.value);
    });

    slugInput.addEventListener('input', () => {
        slugTouched = slugInput.value.trim() !== '';
    });

    if (!slugTouched && nameInput.value.trim() !== '') {
        slugInput.value = slugify(nameInput.value);
    }
})();
</script>
<?php require __DIR__ . '/../layouts/admin_footer.php'; ?>
